CREATE TABLE state_entity
(
    id          BIGINT GENERATED BY DEFAULT AS identity PRIMARY key,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    mail        TEXT,
    name        TEXT,
    description TEXT
);